# Git Project Planner Configuration
# https://github.com/mnemoverse/git-project-planner

# Repository information
repository:
  owner: "mnemoverse"
  name: "smartkeys-v2"

# Directory paths (relative to repository root)
paths:
  tasks: "tasks"              # Task specifications directory
  planning: "planning"        # Sprint planning directory
  docs: "docs/planning"       # Planning documentation

# GitHub Project integration
project:
  number: 11                  # GitHub Project board number
  
# Task prefixes for different types
task_prefixes:
  feature: "SMK"              # Feature tasks (SMK-001, SMK-002, etc.)
  planning: "PS"              # Planning system tasks (PS-001, etc.)
  bugfix: "BUG"               # Bug fixes
  
# Sprint configuration
sprint:
  duration_days: 7            # Sprint duration in days
  start_day: "Thursday"       # Week start day
  
# Workflow preferences
workflow:
  auto_sync_issues: true      # Automatically sync with GitHub Issues
  archive_completed: true     # Archive completed sprints
  require_estimates: true     # Require time estimates for tasks
